In [1]:
import pandas as pd
import numpy as np

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a = np.arange(4 * 888).reshape(888, 4)
a

array([[   0,    1,    2,    3],
       [   4,    5,    6,    7],
       [   8,    9,   10,   11],
       ...,
       [3540, 3541, 3542, 3543],
       [3544, 3545, 3546, 3547],
       [3548, 3549, 3550, 3551]])

In [4]:
a = a + 1
list('ABCD')

['A', 'B', 'C', 'D']

In [5]:
df = pd.DataFrame(a, columns=list('ABCD'))
df

A     B     C     D
0       1     2     3     4
1       5     6     7     8
2       9    10    11    12
3      13    14    15    16
4      17    18    19    20
..    ...   ...   ...   ...
883  3533  3534  3535  3536
884  3537  3538  3539  3540
885  3541  3542  3543  3544
886  3545  3546  3547  3548
887  3549  3550  3551  3552

[888 rows x 4 columns]

In [6]:
df.head()

A   B   C   D
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16
4  17  18  19  20

In [7]:
df.head(3)

A   B   C   D
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12

In [8]:
df.tail()

A     B     C     D
883  3533  3534  3535  3536
884  3537  3538  3539  3540
885  3541  3542  3543  3544
886  3545  3546  3547  3548
887  3549  3550  3551  3552

In [9]:
df.tail(3)

A     B     C     D
885  3541  3542  3543  3544
886  3545  3546  3547  3548
887  3549  3550  3551  3552

In [10]:
df.index

RangeIndex(start=0, stop=888, step=1)

In [11]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [12]:
df.describe()

A            B            C            D
count   888.000000   888.000000   888.000000   888.000000
mean   1775.000000  1776.000000  1777.000000  1778.000000
std    1025.951266  1025.951266  1025.951266  1025.951266
min       1.000000     2.000000     3.000000     4.000000
25%     888.000000   889.000000   890.000000   891.000000
50%    1775.000000  1776.000000  1777.000000  1778.000000
75%    2662.000000  2663.000000  2664.000000  2665.000000
max    3549.000000  3550.000000  3551.000000  3552.000000

# Сортировка

In [13]:
a = np.random.rand(888, 4)
df = pd.DataFrame(a, columns=list('ABCD'))
df

A         B         C         D
0    0.416103  0.230197  0.052744  0.641824
1    0.135566  0.512923  0.845464  0.373253
2    0.840328  0.207079  0.577448  0.284003
3    0.503420  0.291522  0.236281  0.397940
4    0.585558  0.970971  0.019752  0.559707
..        ...       ...       ...       ...
883  0.520062  0.975955  0.024820  0.401821
884  0.946750  0.044612  0.378193  0.360500
885  0.823247  0.651466  0.351732  0.688832
886  0.648531  0.899025  0.933409  0.622322
887  0.004623  0.103208  0.381145  0.717003

[888 rows x 4 columns]

In [14]:
df.sort_values('B')

A         B         C         D
365  0.021664  0.000391  0.006258  0.439965
836  0.809761  0.001065  0.191511  0.670731
652  0.654789  0.001321  0.031256  0.751667
403  0.033164  0.002397  0.786453  0.622564
209  0.599948  0.002516  0.493455  0.480738
..        ...       ...       ...       ...
742  0.246957  0.995030  0.257412  0.722528
311  0.171780  0.996114  0.568199  0.935283
41   0.127482  0.996728  0.267848  0.279753
116  0.638816  0.997758  0.144290  0.582588
800  0.660699  0.999993  0.597645  0.102838

[888 rows x 4 columns]

In [15]:
df.sort_values(by = ['B', 'C'])

A         B         C         D
365  0.021664  0.000391  0.006258  0.439965
836  0.809761  0.001065  0.191511  0.670731
652  0.654789  0.001321  0.031256  0.751667
403  0.033164  0.002397  0.786453  0.622564
209  0.599948  0.002516  0.493455  0.480738
..        ...       ...       ...       ...
742  0.246957  0.995030  0.257412  0.722528
311  0.171780  0.996114  0.568199  0.935283
41   0.127482  0.996728  0.267848  0.279753
116  0.638816  0.997758  0.144290  0.582588
800  0.660699  0.999993  0.597645  0.102838

[888 rows x 4 columns]

In [16]:
df.sort_values(by = 'B', ascending = False)

A         B         C         D
800  0.660699  0.999993  0.597645  0.102838
116  0.638816  0.997758  0.144290  0.582588
41   0.127482  0.996728  0.267848  0.279753
311  0.171780  0.996114  0.568199  0.935283
742  0.246957  0.995030  0.257412  0.722528
..        ...       ...       ...       ...
209  0.599948  0.002516  0.493455  0.480738
403  0.033164  0.002397  0.786453  0.622564
652  0.654789  0.001321  0.031256  0.751667
836  0.809761  0.001065  0.191511  0.670731
365  0.021664  0.000391  0.006258  0.439965

[888 rows x 4 columns]

# Получение значений

In [17]:
a = np.arange(4 * 888).reshape(888, 4)
df = pd.DataFrame(a, columns = list('ABCD'))
df.head()

A   B   C   D
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [18]:
# получить значения
df.values

array([[   0,    1,    2,    3],
       [   4,    5,    6,    7],
       [   8,    9,   10,   11],
       ...,
       [3540, 3541, 3542, 3543],
       [3544, 3545, 3546, 3547],
       [3548, 3549, 3550, 3551]])

In [19]:
# получить значения через to_numpy
df.to_numpy()

array([[   0,    1,    2,    3],
       [   4,    5,    6,    7],
       [   8,    9,   10,   11],
       ...,
       [3540, 3541, 3542, 3543],
       [3544, 3545, 3546, 3547],
       [3548, 3549, 3550, 3551]])

In [20]:
# вызвать колонку так предпочтительней
df['A']

0         0
1         4
2         8
3        12
4        16
       ... 
883    3532
884    3536
885    3540
886    3544
887    3548
Name: A, Length: 888, dtype: int32

In [21]:
# вызвать колонку
df.A

0         0
1         4
2         8
3        12
4        16
       ... 
883    3532
884    3536
885    3540
886    3544
887    3548
Name: A, Length: 888, dtype: int32

In [22]:
# выбрать строки и столбцы (срез данных)
df.loc[1:2, 'A':'C']

A  B   C
1  4  5   6
2  8  9  10

In [23]:
# выбрать один элемент
df.loc[0, 'B']

1

In [24]:
# выбрать определенные строки и столбцы (срез данных)
df.loc[[0, 1, 3, 5], 'B':'D']

B   C   D
0   1   2   3
1   5   6   7
3  13  14  15
5  21  22  23

## Получение значений по индексу

In [25]:
df.iloc[:]

A     B     C     D
0       0     1     2     3
1       4     5     6     7
2       8     9    10    11
3      12    13    14    15
4      16    17    18    19
..    ...   ...   ...   ...
883  3532  3533  3534  3535
884  3536  3537  3538  3539
885  3540  3541  3542  3543
886  3544  3545  3546  3547
887  3548  3549  3550  3551

[888 rows x 4 columns]

In [26]:
# вызов по индексу столбца
df.iloc[:, 2]

0         2
1         6
2        10
3        14
4        18
       ... 
883    3534
884    3538
885    3542
886    3546
887    3550
Name: C, Length: 888, dtype: int32

In [27]:
# вызывает 2-ю строку
df.iloc[2]

A     8
B     9
C    10
D    11
Name: 2, dtype: int32

In [28]:
df.iloc[2,:]

A     8
B     9
C    10
D    11
Name: 2, dtype: int32

In [29]:
# выбираем значения по индексу столбца
df.values[:,2]

array([   2,    6,   10,   14,   18,   22,   26,   30,   34,   38,   42,
         46,   50,   54,   58,   62,   66,   70,   74,   78,   82,   86,
         90,   94,   98,  102,  106,  110,  114,  118,  122,  126,  130,
        134,  138,  142,  146,  150,  154,  158,  162,  166,  170,  174,
        178,  182,  186,  190,  194,  198,  202,  206,  210,  214,  218,
        222,  226,  230,  234,  238,  242,  246,  250,  254,  258,  262,
        266,  270,  274,  278,  282,  286,  290,  294,  298,  302,  306,
        310,  314,  318,  322,  326,  330,  334,  338,  342,  346,  350,
        354,  358,  362,  366,  370,  374,  378,  382,  386,  390,  394,
        398,  402,  406,  410,  414,  418,  422,  426,  430,  434,  438,
        442,  446,  450,  454,  458,  462,  466,  470,  474,  478,  482,
        486,  490,  494,  498,  502,  506,  510,  514,  518,  522,  526,
        530,  534,  538,  542,  546,  550,  554,  558,  562,  566,  570,
        574,  578,  582,  586,  590,  594,  598,  6

## Фильтрация по маске

In [30]:
# проверка всех элементов
df['A'] > 300

0      False
1      False
2      False
3      False
4      False
       ...  
883     True
884     True
885     True
886     True
887     True
Name: A, Length: 888, dtype: bool

In [31]:
# используем условный операток как маску
df[df['A'] > 300]

A     B     C     D
76    304   305   306   307
77    308   309   310   311
78    312   313   314   315
79    316   317   318   319
80    320   321   322   323
..    ...   ...   ...   ...
883  3532  3533  3534  3535
884  3536  3537  3538  3539
885  3540  3541  3542  3543
886  3544  3545  3546  3547
887  3548  3549  3550  3551

[812 rows x 4 columns]

## Сохранение в csv файл

In [32]:
df.to_csv('general_data.csv')

In [36]:
df.to_csv('C:/BMSTU_coding/bmstu_coding/general_data.csv', index = False)